// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asocxtsvxpzlmnuujsed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzb2N4dHN2eHB6bG1udXVqc2VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTI0MzYsImV4cCI6MjA2MzkyODQzNn0.htKYfMAHxtL5KqQD8Vu4-fQZi8bymNAP0HaF9cI2kpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);